"""initial intake workflow schema

Revision ID: 2bebefca9627
Revises:
Create Date: 2026-07-09 21:19:20.843447

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2bebefca9627'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.String(length=50), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('matched_cases', sa.Integer(), nullable=False),
    sa.Column('routing_accuracy', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_dataset'), 'eval_runs', ['dataset'], unique=False)
    op.create_table('intake_cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('latest_extraction_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_cases_external_reference'), 'intake_cases', ['external_reference'], unique=True)
    op.create_index(op.f('ix_intake_cases_status'), 'intake_cases', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_pages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sha256', name='uq_case_document_hash'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('eval_case_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eval_run_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('expected_status', sa.String(length=50), nullable=False),
    sa.Column('actual_status', sa.String(length=50), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_case_results_eval_run_id'), 'eval_case_results', ['eval_run_id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('route_tier', sa.String(length=20), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('schema_version', sa.String(length=30), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_case_id'), 'model_runs', ['case_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'idempotency_key', name='uq_processing_job_key')
    )
    op.create_index(op.f('ix_processing_jobs_case_id'), 'processing_jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_correlation_id'), 'processing_jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('corrections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_case_id'), 'review_decisions', ['case_id'], unique=False)
    op.create_table('validation_issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_issues_case_id'), 'validation_issues', ['case_id'], unique=False)
    op.create_index(op.f('ix_validation_issues_code'), 'validation_issues', ['code'], unique=False)
    op.create_table('extraction_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('model_run_id', sa.String(length=32), nullable=False),
    sa.Column('normalized_record', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['intake_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_results_case_id'), 'extraction_results', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_results_case_id'), table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index(op.f('ix_validation_issues_code'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_case_id'), table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index(op.f('ix_review_decisions_case_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_correlation_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_case_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_model_runs_case_id'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_eval_case_results_eval_run_id'), table_name='eval_case_results')
    op.drop_table('eval_case_results')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_intake_cases_status'), table_name='intake_cases')
    op.drop_index(op.f('ix_intake_cases_external_reference'), table_name='intake_cases')
    op.drop_table('intake_cases')
    op.drop_index(op.f('ix_eval_runs_dataset'), table_name='eval_runs')
    op.drop_table('eval_runs')
    # ### end Alembic commands ###
